<form class="form-signin col-md-3" role="form">
    <h2 class="form-signin-heading">Registration</h2>
    <label for="name" class="sr-only">Name</label>
    <input type="name" class="form-control" placeholder="Your Name" />
    <label for="email" class="sr-only">Email</label>
    <input type="email" class="form-control" placeholder="Your Email" />
    <label for="password" class="sr-only">Password</label>
    <input type="password" class="form-control" placeholder="Enter Password" />
    <label for="retype_password" class="sr-only">Retype Password</label>
    <input type="retype_password" class="form-control" placeholder="Retype Password" />

    <button class="btn btn-lg btn-primary btn-block" type="submit">Register me</button>
</form>